#!/usr/bin/env bash

set -eu
set -o pipefail

URL=https://html.spec.whatwg.org/entities.json

grep '^--' Setup.hs

cat <<EOF
--
-- This file was automatically generated.
--
-- DO NOT EDIT THIS FILE!

module Edify.HTML.Entities (entities) where

import qualified Data.Binary as Binary
import Data.Binary.Instances.Text ()
import Data.Binary.Instances.UnorderedContainers ()

-- | HTML entity map from entity name to text value.
EOF

curl -L "$URL" |
  cabal run --verbose=0 entities
